### ISSUE TITLE
Adding a music recommender

### ISSUE THREAD

**Issue by Garvit1809** [MLH-Fellowship/prep-project-23.MAR.PREP.1#16]
We are up for adding a music recommendation feature according to the user's location's weather, using Spotify API.

**Comment by sumana2001** [comment]
Could you elaborate more on the issue? Like will it recommend playlists or one particular song or will you have a music player embedded in the website?

**Comment by sumana2001** [comment]
Yes @mukhsadr both the teams are working together on both the issues
