### ISSUE TITLE
Add food recommendations based on weather

### ISSUE THREAD

**Issue by samyukthagopalsamy** [MLH-Fellowship/prep-project-23.MAR.PREP.1#17]
We would like to add a feature for recommending food based on the weather at the user's chosen location. 
@Ahmed-Labs @sumana2001

**Comment by sumana2001** [comment]
Could you elaborate more on the issue? Will it based on location as well? Like must try foods of certain places? Also how many options will they be getting? Will it be hardcoded or from some API call?

**Comment by samyukthagopalsamy** [comment]
Currently, we have four categories of food types {`summer`, `fall`, `spring` and `winter`} and associated food recommendation names that are scraped from articles on a website. We use the weather condition code from the API response to determine the appropriate food category. We then randomly recommend the food from the category and display it with an icon or background that represents that category. 

The location is not currently being used to recommend specific local dishes.
