### ISSUE TITLE
Rating recommended songs

### ISSUE THREAD

**Issue by sgoyal5** [MLH-Fellowship/prep-project-23.MAR.PREP.1#22]
This feature would allow users to rate a song from a rating of 1-5. Based on their rating, it would recommend new songs.
For example, if a user rated a song 5, then they would get recommended similar songs.

**Comment by sumana2001** [comment]
Sounds good. Would you like to take this up?

**Comment by sumana2001** [comment]
We are not doing this issue anymore right? @2leila5 @sgoyal5
