### ISSUE TITLE
Give a name to our project

### ISSUE THREAD

**Issue by Arya-Gupta** [MLH-Fellowship/prep-project-23.MAR.PREP.1#38]
Currently, the app simply says - 'React App'. This can be changed to something more creative.

![image](https://user-images.githubusercontent.com/84087089/226984488-881ef7e1-11a8-4970-aec5-7add680450ca.png)

**Comment by sumana2001** [comment]
Yes I feel this could be added along with #34 @mukhsadr @KoichiMin

**Comment by mukhsadr** [comment]
@sumana2001 please assign us! We are working on nav bar and footer and we will take care of it.
